// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Expo = require("expo");

function getInfo($staropt$star, fileUri) {
  var opt = $staropt$star ? $staropt$star[0] : { };
  return Expo.FileSystem.getInfoAsync(fileUri, opt);
}

exports.getInfo = getInfo;
/* expo Not a pure module */
