// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Expo    = require("expo");
var Js_dict = require("bs-platform/lib/js/js_dict.js");

function load(name, path) {
  console.log("[Deprecated] Please use loadAll instead");
  return Expo.Font.loadAsync(name, path);
}

function loadAll(fonts) {
  return Expo.Font.loadAsync(Js_dict.fromArray(fonts));
}

exports.load    = load;
exports.loadAll = loadAll;
/* expo Not a pure module */
