// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Expo           = require("expo");
var Helpers$BsExpo = require("./helpers.js");

function getExpoPushToken() {
  var eta = Expo.Notification.getExpoPushTokenAsync();
  return Helpers$BsExpo.promise_to_result(/* None */0, eta);
}

exports.getExpoPushToken = getExpoPushToken;
/* expo Not a pure module */
