// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Expo                    = require("expo");
var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");

function allow(orient) {
  var tmp;
  if (orient !== 1) {
    if (orient !== 0) {
      throw [
            Caml_builtin_exceptions.match_failure,
            [
              "/Users/rabbit/p/forks/bs-expo/src/screenOrientation.re",
              20,
              2
            ]
          ];
    } else {
      tmp = Expo.ScreenOrientation.ALL;
    }
  } else {
    tmp = Expo.ScreenOrientation.ALL_BUT_UPSIDE_DOWN;
  }
  Expo.ScreenOrientation.allow(tmp);
  return /* () */0;
}

exports.allow = allow;
/* expo Not a pure module */
